
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MyMLModel_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            for (int i = 4001; i < 5000; i++)
            {
                string path = $@"D:\ML\archive\dataset\test_set\cats\cat.{i}.jpg";
                // Create single instance of sample data from first line of dataset for model input
                MyMLModel.ModelInput sampleData = new MyMLModel.ModelInput()
                {
                    ImageSource = path,
                };

                // Make a single prediction on the sample data and print results
                var predictionResult = MyMLModel.Predict(sampleData);

                //Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


                // Console.WriteLine($"ImageSource: {path}");


                //Console.WriteLine($"\n\nPredicted Label value: {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
                //Console.WriteLine("\n\n\n");

                if (predictionResult.Prediction != "cats" || predictionResult.Score[0] < 0.9)
                {
                    Console.WriteLine($"image number:{i}Predicted Label value: {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]");
                }

            }

            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
